# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import etco_pb2 as etco__pb2


class EveTradingCoStub(object):
    """// STATIC ENDPOINTS // // (nextJS static generation / static JS file)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SDETypeData = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/SDETypeData',
                request_serializer=etco__pb2.SDETypeDataRequest.SerializeToString,
                response_deserializer=etco__pb2.SDETypeDataResponse.FromString,
                )
        self.NamedSDETypeData = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/NamedSDETypeData',
                request_serializer=etco__pb2.NamedSDETypeDataRequest.SerializeToString,
                response_deserializer=etco__pb2.NamedSDETypeDataResponse.FromString,
                )
        self.ShopLocations = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/ShopLocations',
                request_serializer=etco__pb2.ShopLocationsRequest.SerializeToString,
                response_deserializer=etco__pb2.ShopLocationsResponse.FromString,
                )
        self.BuybackSystems = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/BuybackSystems',
                request_serializer=etco__pb2.BuybackSystemsRequest.SerializeToString,
                response_deserializer=etco__pb2.BuybackSystemsResponse.FromString,
                )
        self.SDESystems = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/SDESystems',
                request_serializer=etco__pb2.SDESystemsRequest.SerializeToString,
                response_deserializer=etco__pb2.SDESystemsResponse.FromString,
                )
        self.IsAdmin = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/IsAdmin',
                request_serializer=etco__pb2.IsAdminRequest.SerializeToString,
                response_deserializer=etco__pb2.IsAdminResponse.FromString,
                )
        self.ShopPurchaseQueue = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/ShopPurchaseQueue',
                request_serializer=etco__pb2.ShopPurchaseQueueRequest.SerializeToString,
                response_deserializer=etco__pb2.ShopPurchaseQueueResponse.FromString,
                )
        self.ShopContractQueue = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/ShopContractQueue',
                request_serializer=etco__pb2.ShopContractQueueRequest.SerializeToString,
                response_deserializer=etco__pb2.ShopContractQueueResponse.FromString,
                )
        self.BuybackContractQueue = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/BuybackContractQueue',
                request_serializer=etco__pb2.BuybackContractQueueRequest.SerializeToString,
                response_deserializer=etco__pb2.BuybackContractQueueResponse.FromString,
                )
        self.CfgGetAuthList = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/CfgGetAuthList',
                request_serializer=etco__pb2.CfgGetAuthListRequest.SerializeToString,
                response_deserializer=etco__pb2.CfgGetAuthListResponse.FromString,
                )
        self.CfgGetBuybackSystemTypeMapsBuilder = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/CfgGetBuybackSystemTypeMapsBuilder',
                request_serializer=etco__pb2.CfgGetBuybackSystemTypeMapsBuilderRequest.SerializeToString,
                response_deserializer=etco__pb2.CfgGetBuybackSystemTypeMapsBuilderResponse.FromString,
                )
        self.CfgGetShopLocationTypeMapsBuilder = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/CfgGetShopLocationTypeMapsBuilder',
                request_serializer=etco__pb2.CfgGetShopLocationTypeMapsBuilderRequest.SerializeToString,
                response_deserializer=etco__pb2.CfgGetShopLocationTypeMapsBuilderResponse.FromString,
                )
        self.CfgGetBuybackSystems = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/CfgGetBuybackSystems',
                request_serializer=etco__pb2.CfgGetBuybackSystemsRequest.SerializeToString,
                response_deserializer=etco__pb2.CfgGetBuybackSystemsResponse.FromString,
                )
        self.CfgGetShopLocations = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/CfgGetShopLocations',
                request_serializer=etco__pb2.CfgGetShopLocationsRequest.SerializeToString,
                response_deserializer=etco__pb2.CfgGetShopLocationsResponse.FromString,
                )
        self.CfgGetMarkets = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/CfgGetMarkets',
                request_serializer=etco__pb2.CfgGetMarketsRequest.SerializeToString,
                response_deserializer=etco__pb2.CfgGetMarketsResponse.FromString,
                )
        self.CfgGetMarketNames = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/CfgGetMarketNames',
                request_serializer=etco__pb2.CfgGetMarketNamesRequest.SerializeToString,
                response_deserializer=etco__pb2.CfgGetMarketNamesResponse.FromString,
                )
        self.CfgGetBuybackBundleKeys = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/CfgGetBuybackBundleKeys',
                request_serializer=etco__pb2.CfgGetBuybackBundleKeysRequest.SerializeToString,
                response_deserializer=etco__pb2.CfgGetBuybackBundleKeysResponse.FromString,
                )
        self.CfgGetShopBundleKeys = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/CfgGetShopBundleKeys',
                request_serializer=etco__pb2.CfgGetShopBundleKeysRequest.SerializeToString,
                response_deserializer=etco__pb2.CfgGetShopBundleKeysResponse.FromString,
                )
        self.CfgGetConstData = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/CfgGetConstData',
                request_serializer=etco__pb2.CfgGetConstDataRequest.SerializeToString,
                response_deserializer=etco__pb2.CfgGetConstDataResponse.FromString,
                )
        self.CfgSetAuthList = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/CfgSetAuthList',
                request_serializer=etco__pb2.CfgSetAuthListRequest.SerializeToString,
                response_deserializer=etco__pb2.CfgSetAuthListResponse.FromString,
                )
        self.CfgSetConstData = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/CfgSetConstData',
                request_serializer=etco__pb2.CfgSetConstDataRequest.SerializeToString,
                response_deserializer=etco__pb2.CfgSetConstDataResponse.FromString,
                )
        self.CfgMergeBuybackSystemTypeMapsBuilder = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/CfgMergeBuybackSystemTypeMapsBuilder',
                request_serializer=etco__pb2.CfgMergeBuybackSystemTypeMapsBuilderRequest.SerializeToString,
                response_deserializer=etco__pb2.CfgMergeBuybackSystemTypeMapsBuilderResponse.FromString,
                )
        self.CfgMergeShopLocationTypeMapsBuilder = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/CfgMergeShopLocationTypeMapsBuilder',
                request_serializer=etco__pb2.CfgMergeShopLocationTypeMapsBuilderRequest.SerializeToString,
                response_deserializer=etco__pb2.CfgMergeShopLocationTypeMapsBuilderResponse.FromString,
                )
        self.CfgMergeBuybackSystems = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/CfgMergeBuybackSystems',
                request_serializer=etco__pb2.CfgMergeBuybackSystemsRequest.SerializeToString,
                response_deserializer=etco__pb2.CfgMergeBuybackSystemsResponse.FromString,
                )
        self.CfgMergeShopLocations = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/CfgMergeShopLocations',
                request_serializer=etco__pb2.CfgMergeShopLocationsRequest.SerializeToString,
                response_deserializer=etco__pb2.CfgMergeShopLocationsResponse.FromString,
                )
        self.CfgMergeMarkets = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/CfgMergeMarkets',
                request_serializer=etco__pb2.CfgMergeMarketsRequest.SerializeToString,
                response_deserializer=etco__pb2.CfgMergeMarketsResponse.FromString,
                )
        self.ShopDeletePurchases = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/ShopDeletePurchases',
                request_serializer=etco__pb2.ShopDeletePurchasesRequest.SerializeToString,
                response_deserializer=etco__pb2.ShopDeletePurchasesResponse.FromString,
                )
        self.EsiAppLogin = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/EsiAppLogin',
                request_serializer=etco__pb2.EsiAppLoginRequest.SerializeToString,
                response_deserializer=etco__pb2.EsiAppLoginResponse.FromString,
                )
        self.CharacterInfo = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/CharacterInfo',
                request_serializer=etco__pb2.CharacterInfoRequest.SerializeToString,
                response_deserializer=etco__pb2.CharacterInfoResponse.FromString,
                )
        self.CorporationInfo = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/CorporationInfo',
                request_serializer=etco__pb2.CorporationInfoRequest.SerializeToString,
                response_deserializer=etco__pb2.CorporationInfoResponse.FromString,
                )
        self.AllianceInfo = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/AllianceInfo',
                request_serializer=etco__pb2.AllianceInfoRequest.SerializeToString,
                response_deserializer=etco__pb2.AllianceInfoResponse.FromString,
                )
        self.Parse = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/Parse',
                request_serializer=etco__pb2.ParseRequest.SerializeToString,
                response_deserializer=etco__pb2.ParseResponse.FromString,
                )
        self.NewBuybackAppraisal = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/NewBuybackAppraisal',
                request_serializer=etco__pb2.NewBuybackAppraisalRequest.SerializeToString,
                response_deserializer=etco__pb2.NewBuybackAppraisalResponse.FromString,
                )
        self.NewShopAppraisal = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/NewShopAppraisal',
                request_serializer=etco__pb2.NewShopAppraisalRequest.SerializeToString,
                response_deserializer=etco__pb2.NewShopAppraisalResponse.FromString,
                )
        self.UserData = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/UserData',
                request_serializer=etco__pb2.UserDataRequest.SerializeToString,
                response_deserializer=etco__pb2.UserDataResponse.FromString,
                )
        self.ShopInventory = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/ShopInventory',
                request_serializer=etco__pb2.ShopInventoryRequest.SerializeToString,
                response_deserializer=etco__pb2.ShopInventoryResponse.FromString,
                )
        self.ShopMakePurchase = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/ShopMakePurchase',
                request_serializer=etco__pb2.ShopMakePurchaseRequest.SerializeToString,
                response_deserializer=etco__pb2.ShopMakePurchaseResponse.FromString,
                )
        self.ShopCancelPurchase = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/ShopCancelPurchase',
                request_serializer=etco__pb2.ShopCancelPurchaseRequest.SerializeToString,
                response_deserializer=etco__pb2.ShopCancelPurchaseResponse.FromString,
                )
        self.GetBuybackAppraisal = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/GetBuybackAppraisal',
                request_serializer=etco__pb2.GetBuybackAppraisalRequest.SerializeToString,
                response_deserializer=etco__pb2.GetBuybackAppraisalResponse.FromString,
                )
        self.GetShopAppraisal = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/GetShopAppraisal',
                request_serializer=etco__pb2.GetShopAppraisalRequest.SerializeToString,
                response_deserializer=etco__pb2.GetShopAppraisalResponse.FromString,
                )
        self.StatusBuybackAppraisal = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/StatusBuybackAppraisal',
                request_serializer=etco__pb2.StatusBuybackAppraisalRequest.SerializeToString,
                response_deserializer=etco__pb2.StatusBuybackAppraisalResponse.FromString,
                )
        self.StatusShopAppraisal = channel.unary_unary(
                '/eve_trading_co_proto.EveTradingCo/StatusShopAppraisal',
                request_serializer=etco__pb2.StatusShopAppraisalRequest.SerializeToString,
                response_deserializer=etco__pb2.StatusShopAppraisalResponse.FromString,
                )


class EveTradingCoServicer(object):
    """// STATIC ENDPOINTS // // (nextJS static generation / static JS file)
    """

    def SDETypeData(self, request, context):
        """lists every SDE type that is published and has a market group
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NamedSDETypeData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShopLocations(self, request, context):
        """returns a list of all valid shop locations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuybackSystems(self, request, context):
        """returns a list of all valid buyback systems
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SDESystems(self, request, context):
        """returns a list of all systems
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsAdmin(self, request, context):
        """// ADMIN ENDPOINTS // //

        simply returns whether the user is an admin
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShopPurchaseQueue(self, request, context):
        """lists the purchase order queue (purchase orders with no contract)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShopContractQueue(self, request, context):
        """lists active contracts, and, optionally, their original appraisals, new prices, and location info
        purchase queue + contract
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuybackContractQueue(self, request, context):
        """contracts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CfgGetAuthList(self, request, context):
        """lists the request config data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CfgGetBuybackSystemTypeMapsBuilder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CfgGetShopLocationTypeMapsBuilder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CfgGetBuybackSystems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CfgGetShopLocations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CfgGetMarkets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CfgGetMarketNames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CfgGetBuybackBundleKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CfgGetShopBundleKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CfgGetConstData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CfgSetAuthList(self, request, context):
        """replaces the existing config data with the given config data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CfgSetConstData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CfgMergeBuybackSystemTypeMapsBuilder(self, request, context):
        """merges the given config data into the existing config data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CfgMergeShopLocationTypeMapsBuilder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CfgMergeBuybackSystems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CfgMergeShopLocations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CfgMergeMarkets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShopDeletePurchases(self, request, context):
        """cancels the purchase orders for the given codes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EsiAppLogin(self, request, context):
        """logs into the requested app
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CharacterInfo(self, request, context):
        """// USER ENDPOINTS // //

        returns entity info for the given entity id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CorporationInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllianceInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Parse(self, request, context):
        """parses an input string into a list of named basic items
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewBuybackAppraisal(self, request, context):
        """returns a buyback appraisal for the provided items and its code (if saved)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewShopAppraisal(self, request, context):
        """returns a shop appraisal for the provided items
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserData(self, request, context):
        """returns the users appraisal codes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShopInventory(self, request, context):
        """returns purchasable items for the given location
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShopMakePurchase(self, request, context):
        """places a purchase order for the given items and location
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShopCancelPurchase(self, request, context):
        """cancel the purchase order for the given code
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuybackAppraisal(self, request, context):
        """// ADMIN / USER ENDPOINTS // // (override via parameters)

        returns the appraisal for the given code
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShopAppraisal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatusBuybackAppraisal(self, request, context):
        """returns the status for the given code
        only the character that made the appraisal is authenticated (unless admin is true)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatusShopAppraisal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EveTradingCoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SDETypeData': grpc.unary_unary_rpc_method_handler(
                    servicer.SDETypeData,
                    request_deserializer=etco__pb2.SDETypeDataRequest.FromString,
                    response_serializer=etco__pb2.SDETypeDataResponse.SerializeToString,
            ),
            'NamedSDETypeData': grpc.unary_unary_rpc_method_handler(
                    servicer.NamedSDETypeData,
                    request_deserializer=etco__pb2.NamedSDETypeDataRequest.FromString,
                    response_serializer=etco__pb2.NamedSDETypeDataResponse.SerializeToString,
            ),
            'ShopLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.ShopLocations,
                    request_deserializer=etco__pb2.ShopLocationsRequest.FromString,
                    response_serializer=etco__pb2.ShopLocationsResponse.SerializeToString,
            ),
            'BuybackSystems': grpc.unary_unary_rpc_method_handler(
                    servicer.BuybackSystems,
                    request_deserializer=etco__pb2.BuybackSystemsRequest.FromString,
                    response_serializer=etco__pb2.BuybackSystemsResponse.SerializeToString,
            ),
            'SDESystems': grpc.unary_unary_rpc_method_handler(
                    servicer.SDESystems,
                    request_deserializer=etco__pb2.SDESystemsRequest.FromString,
                    response_serializer=etco__pb2.SDESystemsResponse.SerializeToString,
            ),
            'IsAdmin': grpc.unary_unary_rpc_method_handler(
                    servicer.IsAdmin,
                    request_deserializer=etco__pb2.IsAdminRequest.FromString,
                    response_serializer=etco__pb2.IsAdminResponse.SerializeToString,
            ),
            'ShopPurchaseQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.ShopPurchaseQueue,
                    request_deserializer=etco__pb2.ShopPurchaseQueueRequest.FromString,
                    response_serializer=etco__pb2.ShopPurchaseQueueResponse.SerializeToString,
            ),
            'ShopContractQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.ShopContractQueue,
                    request_deserializer=etco__pb2.ShopContractQueueRequest.FromString,
                    response_serializer=etco__pb2.ShopContractQueueResponse.SerializeToString,
            ),
            'BuybackContractQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.BuybackContractQueue,
                    request_deserializer=etco__pb2.BuybackContractQueueRequest.FromString,
                    response_serializer=etco__pb2.BuybackContractQueueResponse.SerializeToString,
            ),
            'CfgGetAuthList': grpc.unary_unary_rpc_method_handler(
                    servicer.CfgGetAuthList,
                    request_deserializer=etco__pb2.CfgGetAuthListRequest.FromString,
                    response_serializer=etco__pb2.CfgGetAuthListResponse.SerializeToString,
            ),
            'CfgGetBuybackSystemTypeMapsBuilder': grpc.unary_unary_rpc_method_handler(
                    servicer.CfgGetBuybackSystemTypeMapsBuilder,
                    request_deserializer=etco__pb2.CfgGetBuybackSystemTypeMapsBuilderRequest.FromString,
                    response_serializer=etco__pb2.CfgGetBuybackSystemTypeMapsBuilderResponse.SerializeToString,
            ),
            'CfgGetShopLocationTypeMapsBuilder': grpc.unary_unary_rpc_method_handler(
                    servicer.CfgGetShopLocationTypeMapsBuilder,
                    request_deserializer=etco__pb2.CfgGetShopLocationTypeMapsBuilderRequest.FromString,
                    response_serializer=etco__pb2.CfgGetShopLocationTypeMapsBuilderResponse.SerializeToString,
            ),
            'CfgGetBuybackSystems': grpc.unary_unary_rpc_method_handler(
                    servicer.CfgGetBuybackSystems,
                    request_deserializer=etco__pb2.CfgGetBuybackSystemsRequest.FromString,
                    response_serializer=etco__pb2.CfgGetBuybackSystemsResponse.SerializeToString,
            ),
            'CfgGetShopLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.CfgGetShopLocations,
                    request_deserializer=etco__pb2.CfgGetShopLocationsRequest.FromString,
                    response_serializer=etco__pb2.CfgGetShopLocationsResponse.SerializeToString,
            ),
            'CfgGetMarkets': grpc.unary_unary_rpc_method_handler(
                    servicer.CfgGetMarkets,
                    request_deserializer=etco__pb2.CfgGetMarketsRequest.FromString,
                    response_serializer=etco__pb2.CfgGetMarketsResponse.SerializeToString,
            ),
            'CfgGetMarketNames': grpc.unary_unary_rpc_method_handler(
                    servicer.CfgGetMarketNames,
                    request_deserializer=etco__pb2.CfgGetMarketNamesRequest.FromString,
                    response_serializer=etco__pb2.CfgGetMarketNamesResponse.SerializeToString,
            ),
            'CfgGetBuybackBundleKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.CfgGetBuybackBundleKeys,
                    request_deserializer=etco__pb2.CfgGetBuybackBundleKeysRequest.FromString,
                    response_serializer=etco__pb2.CfgGetBuybackBundleKeysResponse.SerializeToString,
            ),
            'CfgGetShopBundleKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.CfgGetShopBundleKeys,
                    request_deserializer=etco__pb2.CfgGetShopBundleKeysRequest.FromString,
                    response_serializer=etco__pb2.CfgGetShopBundleKeysResponse.SerializeToString,
            ),
            'CfgGetConstData': grpc.unary_unary_rpc_method_handler(
                    servicer.CfgGetConstData,
                    request_deserializer=etco__pb2.CfgGetConstDataRequest.FromString,
                    response_serializer=etco__pb2.CfgGetConstDataResponse.SerializeToString,
            ),
            'CfgSetAuthList': grpc.unary_unary_rpc_method_handler(
                    servicer.CfgSetAuthList,
                    request_deserializer=etco__pb2.CfgSetAuthListRequest.FromString,
                    response_serializer=etco__pb2.CfgSetAuthListResponse.SerializeToString,
            ),
            'CfgSetConstData': grpc.unary_unary_rpc_method_handler(
                    servicer.CfgSetConstData,
                    request_deserializer=etco__pb2.CfgSetConstDataRequest.FromString,
                    response_serializer=etco__pb2.CfgSetConstDataResponse.SerializeToString,
            ),
            'CfgMergeBuybackSystemTypeMapsBuilder': grpc.unary_unary_rpc_method_handler(
                    servicer.CfgMergeBuybackSystemTypeMapsBuilder,
                    request_deserializer=etco__pb2.CfgMergeBuybackSystemTypeMapsBuilderRequest.FromString,
                    response_serializer=etco__pb2.CfgMergeBuybackSystemTypeMapsBuilderResponse.SerializeToString,
            ),
            'CfgMergeShopLocationTypeMapsBuilder': grpc.unary_unary_rpc_method_handler(
                    servicer.CfgMergeShopLocationTypeMapsBuilder,
                    request_deserializer=etco__pb2.CfgMergeShopLocationTypeMapsBuilderRequest.FromString,
                    response_serializer=etco__pb2.CfgMergeShopLocationTypeMapsBuilderResponse.SerializeToString,
            ),
            'CfgMergeBuybackSystems': grpc.unary_unary_rpc_method_handler(
                    servicer.CfgMergeBuybackSystems,
                    request_deserializer=etco__pb2.CfgMergeBuybackSystemsRequest.FromString,
                    response_serializer=etco__pb2.CfgMergeBuybackSystemsResponse.SerializeToString,
            ),
            'CfgMergeShopLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.CfgMergeShopLocations,
                    request_deserializer=etco__pb2.CfgMergeShopLocationsRequest.FromString,
                    response_serializer=etco__pb2.CfgMergeShopLocationsResponse.SerializeToString,
            ),
            'CfgMergeMarkets': grpc.unary_unary_rpc_method_handler(
                    servicer.CfgMergeMarkets,
                    request_deserializer=etco__pb2.CfgMergeMarketsRequest.FromString,
                    response_serializer=etco__pb2.CfgMergeMarketsResponse.SerializeToString,
            ),
            'ShopDeletePurchases': grpc.unary_unary_rpc_method_handler(
                    servicer.ShopDeletePurchases,
                    request_deserializer=etco__pb2.ShopDeletePurchasesRequest.FromString,
                    response_serializer=etco__pb2.ShopDeletePurchasesResponse.SerializeToString,
            ),
            'EsiAppLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.EsiAppLogin,
                    request_deserializer=etco__pb2.EsiAppLoginRequest.FromString,
                    response_serializer=etco__pb2.EsiAppLoginResponse.SerializeToString,
            ),
            'CharacterInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.CharacterInfo,
                    request_deserializer=etco__pb2.CharacterInfoRequest.FromString,
                    response_serializer=etco__pb2.CharacterInfoResponse.SerializeToString,
            ),
            'CorporationInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.CorporationInfo,
                    request_deserializer=etco__pb2.CorporationInfoRequest.FromString,
                    response_serializer=etco__pb2.CorporationInfoResponse.SerializeToString,
            ),
            'AllianceInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.AllianceInfo,
                    request_deserializer=etco__pb2.AllianceInfoRequest.FromString,
                    response_serializer=etco__pb2.AllianceInfoResponse.SerializeToString,
            ),
            'Parse': grpc.unary_unary_rpc_method_handler(
                    servicer.Parse,
                    request_deserializer=etco__pb2.ParseRequest.FromString,
                    response_serializer=etco__pb2.ParseResponse.SerializeToString,
            ),
            'NewBuybackAppraisal': grpc.unary_unary_rpc_method_handler(
                    servicer.NewBuybackAppraisal,
                    request_deserializer=etco__pb2.NewBuybackAppraisalRequest.FromString,
                    response_serializer=etco__pb2.NewBuybackAppraisalResponse.SerializeToString,
            ),
            'NewShopAppraisal': grpc.unary_unary_rpc_method_handler(
                    servicer.NewShopAppraisal,
                    request_deserializer=etco__pb2.NewShopAppraisalRequest.FromString,
                    response_serializer=etco__pb2.NewShopAppraisalResponse.SerializeToString,
            ),
            'UserData': grpc.unary_unary_rpc_method_handler(
                    servicer.UserData,
                    request_deserializer=etco__pb2.UserDataRequest.FromString,
                    response_serializer=etco__pb2.UserDataResponse.SerializeToString,
            ),
            'ShopInventory': grpc.unary_unary_rpc_method_handler(
                    servicer.ShopInventory,
                    request_deserializer=etco__pb2.ShopInventoryRequest.FromString,
                    response_serializer=etco__pb2.ShopInventoryResponse.SerializeToString,
            ),
            'ShopMakePurchase': grpc.unary_unary_rpc_method_handler(
                    servicer.ShopMakePurchase,
                    request_deserializer=etco__pb2.ShopMakePurchaseRequest.FromString,
                    response_serializer=etco__pb2.ShopMakePurchaseResponse.SerializeToString,
            ),
            'ShopCancelPurchase': grpc.unary_unary_rpc_method_handler(
                    servicer.ShopCancelPurchase,
                    request_deserializer=etco__pb2.ShopCancelPurchaseRequest.FromString,
                    response_serializer=etco__pb2.ShopCancelPurchaseResponse.SerializeToString,
            ),
            'GetBuybackAppraisal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuybackAppraisal,
                    request_deserializer=etco__pb2.GetBuybackAppraisalRequest.FromString,
                    response_serializer=etco__pb2.GetBuybackAppraisalResponse.SerializeToString,
            ),
            'GetShopAppraisal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShopAppraisal,
                    request_deserializer=etco__pb2.GetShopAppraisalRequest.FromString,
                    response_serializer=etco__pb2.GetShopAppraisalResponse.SerializeToString,
            ),
            'StatusBuybackAppraisal': grpc.unary_unary_rpc_method_handler(
                    servicer.StatusBuybackAppraisal,
                    request_deserializer=etco__pb2.StatusBuybackAppraisalRequest.FromString,
                    response_serializer=etco__pb2.StatusBuybackAppraisalResponse.SerializeToString,
            ),
            'StatusShopAppraisal': grpc.unary_unary_rpc_method_handler(
                    servicer.StatusShopAppraisal,
                    request_deserializer=etco__pb2.StatusShopAppraisalRequest.FromString,
                    response_serializer=etco__pb2.StatusShopAppraisalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eve_trading_co_proto.EveTradingCo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EveTradingCo(object):
    """// STATIC ENDPOINTS // // (nextJS static generation / static JS file)
    """

    @staticmethod
    def SDETypeData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/SDETypeData',
            etco__pb2.SDETypeDataRequest.SerializeToString,
            etco__pb2.SDETypeDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NamedSDETypeData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/NamedSDETypeData',
            etco__pb2.NamedSDETypeDataRequest.SerializeToString,
            etco__pb2.NamedSDETypeDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShopLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/ShopLocations',
            etco__pb2.ShopLocationsRequest.SerializeToString,
            etco__pb2.ShopLocationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BuybackSystems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/BuybackSystems',
            etco__pb2.BuybackSystemsRequest.SerializeToString,
            etco__pb2.BuybackSystemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SDESystems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/SDESystems',
            etco__pb2.SDESystemsRequest.SerializeToString,
            etco__pb2.SDESystemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IsAdmin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/IsAdmin',
            etco__pb2.IsAdminRequest.SerializeToString,
            etco__pb2.IsAdminResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShopPurchaseQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/ShopPurchaseQueue',
            etco__pb2.ShopPurchaseQueueRequest.SerializeToString,
            etco__pb2.ShopPurchaseQueueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShopContractQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/ShopContractQueue',
            etco__pb2.ShopContractQueueRequest.SerializeToString,
            etco__pb2.ShopContractQueueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BuybackContractQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/BuybackContractQueue',
            etco__pb2.BuybackContractQueueRequest.SerializeToString,
            etco__pb2.BuybackContractQueueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CfgGetAuthList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/CfgGetAuthList',
            etco__pb2.CfgGetAuthListRequest.SerializeToString,
            etco__pb2.CfgGetAuthListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CfgGetBuybackSystemTypeMapsBuilder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/CfgGetBuybackSystemTypeMapsBuilder',
            etco__pb2.CfgGetBuybackSystemTypeMapsBuilderRequest.SerializeToString,
            etco__pb2.CfgGetBuybackSystemTypeMapsBuilderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CfgGetShopLocationTypeMapsBuilder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/CfgGetShopLocationTypeMapsBuilder',
            etco__pb2.CfgGetShopLocationTypeMapsBuilderRequest.SerializeToString,
            etco__pb2.CfgGetShopLocationTypeMapsBuilderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CfgGetBuybackSystems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/CfgGetBuybackSystems',
            etco__pb2.CfgGetBuybackSystemsRequest.SerializeToString,
            etco__pb2.CfgGetBuybackSystemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CfgGetShopLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/CfgGetShopLocations',
            etco__pb2.CfgGetShopLocationsRequest.SerializeToString,
            etco__pb2.CfgGetShopLocationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CfgGetMarkets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/CfgGetMarkets',
            etco__pb2.CfgGetMarketsRequest.SerializeToString,
            etco__pb2.CfgGetMarketsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CfgGetMarketNames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/CfgGetMarketNames',
            etco__pb2.CfgGetMarketNamesRequest.SerializeToString,
            etco__pb2.CfgGetMarketNamesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CfgGetBuybackBundleKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/CfgGetBuybackBundleKeys',
            etco__pb2.CfgGetBuybackBundleKeysRequest.SerializeToString,
            etco__pb2.CfgGetBuybackBundleKeysResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CfgGetShopBundleKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/CfgGetShopBundleKeys',
            etco__pb2.CfgGetShopBundleKeysRequest.SerializeToString,
            etco__pb2.CfgGetShopBundleKeysResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CfgGetConstData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/CfgGetConstData',
            etco__pb2.CfgGetConstDataRequest.SerializeToString,
            etco__pb2.CfgGetConstDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CfgSetAuthList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/CfgSetAuthList',
            etco__pb2.CfgSetAuthListRequest.SerializeToString,
            etco__pb2.CfgSetAuthListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CfgSetConstData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/CfgSetConstData',
            etco__pb2.CfgSetConstDataRequest.SerializeToString,
            etco__pb2.CfgSetConstDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CfgMergeBuybackSystemTypeMapsBuilder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/CfgMergeBuybackSystemTypeMapsBuilder',
            etco__pb2.CfgMergeBuybackSystemTypeMapsBuilderRequest.SerializeToString,
            etco__pb2.CfgMergeBuybackSystemTypeMapsBuilderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CfgMergeShopLocationTypeMapsBuilder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/CfgMergeShopLocationTypeMapsBuilder',
            etco__pb2.CfgMergeShopLocationTypeMapsBuilderRequest.SerializeToString,
            etco__pb2.CfgMergeShopLocationTypeMapsBuilderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CfgMergeBuybackSystems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/CfgMergeBuybackSystems',
            etco__pb2.CfgMergeBuybackSystemsRequest.SerializeToString,
            etco__pb2.CfgMergeBuybackSystemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CfgMergeShopLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/CfgMergeShopLocations',
            etco__pb2.CfgMergeShopLocationsRequest.SerializeToString,
            etco__pb2.CfgMergeShopLocationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CfgMergeMarkets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/CfgMergeMarkets',
            etco__pb2.CfgMergeMarketsRequest.SerializeToString,
            etco__pb2.CfgMergeMarketsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShopDeletePurchases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/ShopDeletePurchases',
            etco__pb2.ShopDeletePurchasesRequest.SerializeToString,
            etco__pb2.ShopDeletePurchasesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EsiAppLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/EsiAppLogin',
            etco__pb2.EsiAppLoginRequest.SerializeToString,
            etco__pb2.EsiAppLoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CharacterInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/CharacterInfo',
            etco__pb2.CharacterInfoRequest.SerializeToString,
            etco__pb2.CharacterInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CorporationInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/CorporationInfo',
            etco__pb2.CorporationInfoRequest.SerializeToString,
            etco__pb2.CorporationInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AllianceInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/AllianceInfo',
            etco__pb2.AllianceInfoRequest.SerializeToString,
            etco__pb2.AllianceInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Parse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/Parse',
            etco__pb2.ParseRequest.SerializeToString,
            etco__pb2.ParseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NewBuybackAppraisal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/NewBuybackAppraisal',
            etco__pb2.NewBuybackAppraisalRequest.SerializeToString,
            etco__pb2.NewBuybackAppraisalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NewShopAppraisal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/NewShopAppraisal',
            etco__pb2.NewShopAppraisalRequest.SerializeToString,
            etco__pb2.NewShopAppraisalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UserData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/UserData',
            etco__pb2.UserDataRequest.SerializeToString,
            etco__pb2.UserDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShopInventory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/ShopInventory',
            etco__pb2.ShopInventoryRequest.SerializeToString,
            etco__pb2.ShopInventoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShopMakePurchase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/ShopMakePurchase',
            etco__pb2.ShopMakePurchaseRequest.SerializeToString,
            etco__pb2.ShopMakePurchaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShopCancelPurchase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/ShopCancelPurchase',
            etco__pb2.ShopCancelPurchaseRequest.SerializeToString,
            etco__pb2.ShopCancelPurchaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBuybackAppraisal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/GetBuybackAppraisal',
            etco__pb2.GetBuybackAppraisalRequest.SerializeToString,
            etco__pb2.GetBuybackAppraisalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetShopAppraisal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/GetShopAppraisal',
            etco__pb2.GetShopAppraisalRequest.SerializeToString,
            etco__pb2.GetShopAppraisalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StatusBuybackAppraisal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/StatusBuybackAppraisal',
            etco__pb2.StatusBuybackAppraisalRequest.SerializeToString,
            etco__pb2.StatusBuybackAppraisalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StatusShopAppraisal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/eve_trading_co_proto.EveTradingCo/StatusShopAppraisal',
            etco__pb2.StatusShopAppraisalRequest.SerializeToString,
            etco__pb2.StatusShopAppraisalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
